trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/employees/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the user stories, add a path for each in urlpatterns

app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path('new/', views.create, name="create"),
    path('edit_profile/', views.edit_profile, name="edit_profile"),
    path('<int:customer_id>/confirm/', views.confirm, name="confirm"),
]

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding Django's built in routes (login and logout). Notice there is no 'login' function in accounts/views.py. Django takes care of this for us.
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate trach_collector/views.py for more info
    path('', views.group_redirect, name='home')
]

trash_collector/employees/models.py
from django.db import models

# Create your models here.

class Employee(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey('accounts.User', blank=True, null=True, on_delete=models.CASCADE)
    address = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=5)

    def __str__(self):
        return self.name

trash_collector/employees/views.py
# from trash_collector.customers.views import one_time_pickup
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.apps import apps
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist
from datetime import date
from .models import Employee



def index(request):
    logged_in_user = request.user
    try:
        logged_in_employee = Employee.objects.get(user=logged_in_user)

        today = date.today()
        
        Customer = apps.get_model('customers.Customer')

        # Filters customers based on zip code, pick up day, and suspension status
        matching_zip = Customer.objects.filter(zip_code = logged_in_employee.zip_code)
        weekly_filter = matching_zip.filter(weekly_pickup = today.strftime("%A"))
        one_time_filter = matching_zip.filter(one_time_pickup = today.strftime("%Y-%m-%d"))
        complete_filter = []
        for customer in weekly_filter:
            if customer.suspend_end == None and customer.suspend_end == None:
                complete_filter.append(customer)
            elif today > customer.suspend_end or today < customer.suspend_start:
                complete_filter.append(customer)
            else:
                pass
        for customer in one_time_filter:
            if customer.suspend_end == None and customer.suspend_end == None:
                complete_filter.append(customer)
            elif today > customer.suspend_end or today < customer.suspend_start:
                complete_filter.append(customer)   
            else:
                pass
        for customer in complete_filter:
            if customer.date_of_last_pickup == today:
                complete_filter.remove(customer)
        if len(complete_filter) == 1:
            for customer in complete_filter:
                if customer.date_of_last_pickup == today:
                    complete_filter.clear()

        # Sends a list of customers with weekly pickup through context to be displayed on index.html after a search
        search_results = []
        if request.method == "POST":
            search_from_form = request.POST.get('index')
            customer_list = []
            customer_list.append(Customer.objects.all())
            search_results = Customer.objects.filter(weekly_pickup = search_from_form)

        context = {
            'logged_in_employee': logged_in_employee,
            'today': today,
            'complete_filter': complete_filter,
            'search_results': search_results
        }
        return render(request, 'employees/index.html', context)
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse('employees:create'))

def create(request):
    logged_in_user = request.user
    if request.method == "POST":
        name_from_form = request.POST.get('name')
        address_from_form = request.POST.get('address')
        zip_from_form = request.POST.get('zip_code')
        new_employee = Employee(name=name_from_form, user=logged_in_user, address=address_from_form, zip_code=zip_from_form)
        new_employee.save()
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        return render(request, 'employees/create.html')

def edit_profile(request):
    logged_in_user = request.user
    logged_in_employee = Employee.objects.get(user=logged_in_user)
    if request.method == "POST":
        name_from_form = request.POST.get('name')
        address_from_form = request.POST.get('address')
        zip_from_form = request.POST.get('zip_code')
        logged_in_employee.name = name_from_form
        logged_in_employee.address = address_from_form
        logged_in_employee.zip_code = zip_from_form
        logged_in_employee.save()
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        context = {
            'logged_in_employee': logged_in_employee
        }
        return render(request, 'employees/edit_profile.html', context)

def confirm(request, customer_id):
    Customer = apps.get_model('customers.Customer')
    customer_update = Customer.objects.get(pk=customer_id)
    customer_update.balance += 20.00
    customer_update.date_of_last_pickup = date.today()
    customer_update.save()
    return HttpResponseRedirect(reverse('employees:index'))

trash_collector/employees/templates/employees/confirm.html
{% extends 'base.html' %}

trash_collector/employees/templates/employees/create.html
{% extends 'base.html' %}

{% block title %} Employee Create {% endblock %}

{% block header %} Please Complete Registration {% endblock %}

{% block content %}

<form action="{% url 'employees:create' %}" method="post">
    {% csrf_token %}
    Name: <input type="text" name="name" id="name"><br />
    Address: <input type="text" name="address" id="address"><br />
    Zip Code: <input type="text" name="zip_code" id="zip_code"><br />
    <input type="submit" value="Register">
</form>

{% endblock %}

trash_collector/employees/templates/employees/edit_profile.html
{% extends 'employees\employee_base.html' %}

{% block title %} Employee Profile Edit {% endblock %}

{% block header %} {% endblock %}

{% block content %}
<br />
<div class='bg-image'>
    <h1>Update Your Information</h1>
    <br />
    <form action="{% url 'employees:edit_profile' %}" method="post">
        {% csrf_token %}
        Name: <input type="name" name="name" id="name">
        <br />
        <br />
        Address: <input type="address" name="address" id="address">
        <br />
        <br />
        Zip Code: <input type="zip_code" name="zip_code" id="zip_code">
        <br />
        <br />
        <input type="submit" value="Submit">
    </form>
</div>

{% endblock %}

trash_collector/employees/templates/employees/employee_base.html
{% extends 'base.html' %}

{% block navbar %}
<a class="nav-item nav-link text-white" href="{% url 'employees:index' %}">Home</a>
<a class="nav-item nav-link text-white" href="{% url 'employees:edit_profile' %}">Edit Profile</a>
{% endblock %}

trash_collector/employees/templates/employees/index.html
{% extends 'employees\employee_base.html' %}

{% block title %} Employee Home {% endblock %}

{% block header %} Employee Portal {% endblock %}

{% block content %}
{% if user.is_authenticated %}
Hello {{ user.username }}!
<br>
<br>
<br>
<div class=row>
    <div class=col-6>
        <h2>Your assigned pickups:</h2>
        <table class='table table-striped border border-dark'>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Address</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for customer in complete_filter %}
                <tr>
                    <td>{{customer.name}}</td>
                    <td>{{customer.address}}</td>
                    <td><a href="{% url 'employees:confirm' customer.id %}">Confirm</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <br>
    <br>
    <br>
    <div class=col-6>
        <form class='card p-1 bg-light' action="{% url 'employees:index' %}" method="post">
            {% csrf_token %}
            Search for customers by day of the week: <input type="text" name="index" id="index"><br />
            <div class='mb-1'>
                <input class='btn btn-primary' type="submit" value="Submit">
            </div>
        </form>

        <br>
        <br>
        <br>
        <h5>Search Results:</h5>
        <table class='table table-striped border border-dark'>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Address</th>
                </tr>
            </thead>
            <tbody>
                {% for customer in search_results %}
                <tr>
                    <td>{{customer.name}}</td>
                    <td>{{customer.address}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% else %}
<p>You are at the employee index, but you are not logged in.</p>
<a href="{% url 'login' %}">Log In</a>
<a href="{% url 'accounts:register' %}">Sign Up</a>
{% endif %}
{% endblock %}