trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/customers/urls.py
from django.urls import path
from . import views

app_name = "customers"
urlpatterns = [
    path('', views.index, name="index"),
    path('new/', views.create, name="create"),
    path('suspend/', views.suspend_service, name="suspend"),
    path('one_time/', views.one_time_pickup, name="one_time"),
    path('edit_profile/', views.edit_profile, name="edit_profile"),
]

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding Django's built in routes (login and logout). Notice there is no 'login' function in accounts/views.py. Django takes care of this for us.
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate trach_collector/views.py for more info
    path('', views.group_redirect, name='home')
]

trash_collector/customers/models.py
from django.db import models

class Customer(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey('accounts.User', blank=True, null=True, on_delete=models.CASCADE)
    address = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=5)
    weekly_pickup = models.CharField(max_length=9)
    one_time_pickup = models.DateField(null=True, blank=True)
    suspend_start = models.DateField(null=True, blank=True)
    suspend_end = models.DateField(null=True, blank=True)
    date_of_last_pickup = models.DateField(null=True, blank=True)
    balance = models.IntegerField(default=0)

    def __str__(self):
        return self.name

trash_collector/customers/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from datetime import date

from .models import Customer

@login_required
def index(request):
    # The following line will get the logged-in user (if there is one) within any view function
    logged_in_user = request.user
    try:
        # This line will return the customer record of the logged-in user if one exists
        logged_in_customer = Customer.objects.get(user=logged_in_user)

        today = date.today()
        
        context = {
            'logged_in_customer': logged_in_customer,
            'today': today
        }
        return render(request, 'customers/index.html', context)
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse('customers:create'))

@login_required
def create(request):
    logged_in_user = request.user
    if request.method == "POST":
        name_from_form = request.POST.get('name')
        address_from_form = request.POST.get('address')
        zip_from_form = request.POST.get('zip_code')
        weekly_from_form = request.POST.get('weekly_pickup')
        new_customer = Customer(name=name_from_form, user=logged_in_user, address=address_from_form, zip_code=zip_from_form, weekly_pickup=weekly_from_form)
        new_customer.save()
        return HttpResponseRedirect(reverse('customers:index'))
    else:
        return render(request, 'customers/create.html')

@login_required
def suspend_service(request):
    logged_in_user = request.user
    logged_in_customer = Customer.objects.get(user=logged_in_user)
    if request.method == "POST":
        start_from_form = request.POST.get('start')
        end_from_form = request.POST.get('end')
        logged_in_customer.suspend_start = start_from_form
        logged_in_customer.suspend_end = end_from_form
        logged_in_customer.save()
        return HttpResponseRedirect(reverse('customers:index'))
    else:
        context = {
            'logged_in_customer': logged_in_customer
        }
        return render(request, 'customers/suspend.html', context)

@login_required
def one_time_pickup(request):
    logged_in_user = request.user
    logged_in_customer = Customer.objects.get(user=logged_in_user)
    if request.method == "POST":
        date_from_form = request.POST.get('date')
        logged_in_customer.one_time_pickup = date_from_form
        logged_in_customer.save()
        return HttpResponseRedirect(reverse('customers:index'))
    else:
        context = {
            'logged_in_customer': logged_in_customer
        }
        return render(request, 'customers/one_time.html', context)

@login_required
def edit_profile(request):
    logged_in_user = request.user
    logged_in_customer = Customer.objects.get(user=logged_in_user)
    if request.method == "POST":
        name_from_form = request.POST.get('name')
        address_from_form = request.POST.get('address')
        zip_from_form = request.POST.get('zip_code')
        logged_in_customer.name = name_from_form
        logged_in_customer.address = address_from_form
        logged_in_customer.zip_code = zip_from_form
        logged_in_customer.save()
        return HttpResponseRedirect(reverse('customers:index'))
    else:
        context = {
            'logged_in_customer': logged_in_customer
        }
        return render(request, 'customers/edit_profile.html', context)

trash_collector/customers/templates/customers/create.html
{% extends 'base.html' %}

{% block title %} Customer Create {% endblock %}

{% block header %} Please Complete Registration {% endblock %}

{% block content %}

<form action="{% url 'customers:create' %}" method="post">
    {% csrf_token %}
    Name: <input type="text" name="name" id="name"><br />
    Address: <input type="text" name="address" id="address"><br />
    Zip Code: <input type="text" name="zip_code" id="zip_code"><br />
    Choose your Weekly Pickup Day: <input type="text" name="weekly_pickup" id="weekly_pickup"><br />
    <input type="submit" value="Register">
</form>

{% endblock %}

trash_collector/customers/templates/customers/customer_base.html
{% extends 'base.html' %}

{% block navbar %}
<a class="nav-item nav-link text-white" href="{% url 'customers:index' %}">Home</a>
<a class="nav-item nav-link text-white" href="{% url 'customers:one_time' %}">One-Time Pick Up</a>
<a class="nav-item nav-link text-white" href="{% url 'customers:suspend' %}">Suspend Service</a>
<a class="nav-item nav-link text-white" href="{% url 'customers:edit_profile' %}">Edit Profile</a>
{% endblock %}

trash_collector/customers/templates/customers/edit_profile.html
{% extends 'customers\customer_base.html' %}

{% block title %} Customer Profile Edit {% endblock %}

{% block header %} Update Your Information {% endblock %}

{% block content %}
<br />
<form action="{% url 'customers:edit_profile' %}" method="post">
    {% csrf_token %}
    Name: <input type="name" name="name" id="name">
    <br />
    <br />
    Address: <input type="address" name="address" id="address">
    <br />
    <br />
    Zip Code: <input type="zip_code" name="zip_code" id="zip_code">
    <br />
    <br />
    <input type="submit" value="Submit">
</form>

{% endblock %}

trash_collector/customers/templates/customers/index.html
{% extends 'customers\customer_base.html' %}

{% block title %} Customer Home {% endblock %}

{% block header %} Customer Portal {% endblock %}

{% block content %}
  {% if user.is_authenticated %}
        Hello {{ logged_in_customer.name }}!<br />
        Address: {{ logged_in_customer.address }} {{logged_in_customer.zip_code }}<br />
        Current balance: $ {{ logged_in_customer.balance }}.00
        <br />
        <br />
        Your Weekly Pickup Day: {{ logged_in_customer.weekly_pickup }}
        <br />
        <br />
        {% if logged_in_customer.one_time_pickup %}
          You have an extra pickup scheduled for {{ logged_in_customer.one_time_pickup }}
        {% endif %}
        <br />
        <br />
        {% if today > logged_in_customer.suspend_start and today < logged_in_customer.suspend_end %}
          Your pickups are suspended until {{ logged_in_customer.suspend_end }}
        {% endif %}

  {% else %}
    <p>You are at the customer index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}

trash_collector/customers/templates/customers/one_time.html
{% extends 'customers\customer_base.html' %}

{% block title %} One Time Pickup {% endblock %}

{% block header %} Choose A One Time Pickup {% endblock %}

{% block content %}
<br />
<form action="{% url 'customers:one_time' %}" method="post">
    {% csrf_token %}
    Date of Pick Up: <input type="date" name="date" id="date">
    <br />
    <br />
    <input type="submit" value="Submit">
</form>

{% endblock %}

trash_collector/customers/templates/customers/suspend.html
{% extends 'customers\customer_base.html' %}

{% block title %} Customer Suspension {% endblock %}

{% block header %} Choose Suspension Dates {% endblock %}

{% block content %}
<br />
<form action="{% url 'customers:suspend' %}" method="post">
    {% csrf_token %}
    Start Date: <input type="date" name="start" id="start">
    <br />
    <br />
    End Date: <input type="date" name="end" id="end">
    <br />
    <br />
    <input type="submit" value="Submit">
</form>

{% endblock %}